### ISSUE TITLE
Improvements to installer

### ISSUE THREAD

**Issue by svenove** [DISCOOS/rescue-me#119]
Just a few minor improvements needed for the installer (rescueme.php):
- Notice: Use of undefined constant SMS_FROM - assumed 'SMS_FROM' in \classes\RescueMe\Properties.php on line 250
- Notice: Use of undefined constant USER_S_CREATED - assumed 'USER_S_CREATED' in \classes\RescueMe\User.php on line 411
- Notice: Use of undefined constant COMPANY_ID - assumed 'COMPANY_ID' in \classes\RescueMe\SMS\UMS.php on line 53
- Notice: Use of undefined constant USER_ID - assumed 'USER_ID' in \classes\RescueMe\SMS\UMS.php on line 54
- Timesone = Timezone
- When running the first time, the admin country-question should default to the same country as set earlier in the same "wizard" ("Default Country Code (ISO2)")
- #85 should also ble implemented on the installer
- Give a better error-message when invalid username/password for the database is supplied

**Comment by kengu** [comment]
Mostly fixed. Closing
