### ISSUE TITLE
Add information about network-provider on SMS-delivery

### ISSUE THREAD

**Issue by svenove** [DISCOOS/rescue-me#121]
#For those SMS-providers that support it (at least Sveve and Nexmo), we should store information about what network-provider the SMS was delivered by.

We could add links to coverage-maps for known SMS-providers as well.
This could help in determining the POA for situations where the SMS is delivered, but no action is taken by the missing person.

**Solution**

- [x] Add network-code to domain model (mobile)
- [x] Add network-code lookup
- [x] Implement Nexmo
- [x] Implement Sveve
- [x] Implement Clickatell
- [x] Implement UMS
- [ ] ~~Add base stations to map~~
- [ ] ~~Add coverage to maps~~

**Comment by kengu** [comment]
@svenove: We now support MCC-MNC lookup. So far, only Nexmo supplies this code with the delivery report. You mentions that Sveve also supports this, but I can't find any documentation about that. As far as I know, UMS does not support this.

**Comment by kengu** [comment]
I've created an account at the [OpenCelliD projec](https://opencellid.org/?ref=welcome-email) and activated the location api which allows us to add base station positions to the map.

**Comment by kengu** [comment]
Implementer, closing.

**Comment by kengu** [comment]
Implemented, closing.
