### ISSUE TITLE
Tracking map is to big, cover other web page items

### ISSUE THREAD

**Issue by Anders55** [DISCOOS/rescue-me#152]
![rescueme map failure](https://cloud.githubusercontent.com/assets/25819162/23618998/7ecb5a56-0292-11e7-8461-d6f8c7db4337.png)

The the tracking map is to big, and covers other web page items.
Have tried with Internet Explorer and Edge on Windows 10, pretty sure I also had the same problem with Chrome on Windows 10.

Have deleted the cache on IE and Edge, still same issue. Have tried with 2 different user logins, same issue.

**Comment by svenove** [comment]
Confirmed on Edge, IE11 and Firefox 51. 
Chrome 56 not affected.

**Comment by svenove** [comment]
Fix possibly found in map.css, remove this line:
https://github.com/DISCOOS/rescue-me/blob/master/src/admin/css/map.css#L10
(tested in Edge, IE11 and FF51)

@kengu could you test and confirm as well? 
If confirmed, could you commit the change to source and update in Production?

**Comment by kengu** [comment]
Patch applied in Prod. @svenove,  can you confirm?

**Comment by svenove** [comment]
Confirmed working in all 4 browsers (hardrefreshed (ctrl+F5)).
