### ISSUE TITLE
Topo2-map has been terminated by Kartverket

### ISSUE THREAD

**Issue by svenove** [DISCOOS/rescue-me#173]
The WMS-service RescueMe uses has been terminated and shut down:
https://kartkatalog.geonorge.no/metadata/uuid/8f381180-1a47-4453-bee7-9a3d64843efa

Have to replace "topo2" with "topo4":
https://github.com/DISCOOS/rescue-me/blob/ba7782030a34abe419d236441df2a60aca90ad2e/src/admin/js/map.js#L37
https://github.com/DISCOOS/rescue-me/blob/ba7782030a34abe419d236441df2a60aca90ad2e/src/admin/js/map.js#L48
https://github.com/DISCOOS/rescue-me/blob/0dace952432dfc657e55167dfb2bc48bea4dae7a/src/classes/RescueMe/Properties.php#L275

**Comment by kengu** [comment]
Fixed.
